### ISSUE TITLE
Deprecate "Credits" page with link to GitHub contributors instead

### ISSUE THREAD

**Issue by joannechester** [civicrm/civicrm-user-guide#107]
Do we have a way of maintning that sort of list, or do we change ot so that we have, say,:

Contributors
v4.7 Michael mcandrew, Joanne Chester, Steve Kessler ...
V4.6 Michael mcandrew, Joanne Chester, Kate Sneed,...

**Comment by michaelmcandrew** [comment]
hmm, well git will do it for us automatically from now on so I don't think we need to duplicate it in that chapter. We could add a heading explaining the above and stating that these are historical credits if you like,..

**Comment by seancolsen** [comment]
My opinion: the work of manually maintaining a "credits" page feels daunting. I would like to rely on the the [GitHub contributor list](https://github.com/civicrm/civicrm-user-guide/graphs/contributors) for this functionality. Is that okay with you @joannechester ? And if so, then can we close this issue?

**Comment by stevekessler** [comment]
I like the GitHub contributor list and unless there is a way to reasonably automate a page I think this is the best option.  We can make a link to the GitHub contributor page on the pages about contributing to the documentation.

**Comment by joannechester** [comment]
The Github contributor list seems like the best way forward.  I think we should retain the existing Credits section, but preface it with something like: "Since 2016 this book has been maintained in Github.  Refer to https://github.com/civicrm/civicrm-user-guide/graphs/contributors for a list of contributors since then.
Contributors prior to 2016 are listed below."

**Comment by seancolsen** [comment]
Agreed.. **Next steps** described perfectly in Joanne's comment above.

**Comment by seamuslee001** [comment]
@seanmadsen can this be closed with #258 merged?

**Comment by seancolsen** [comment]
Yep!
