### ISSUE TITLE
Document "contributions widgets" functionality

### ISSUE THREAD

**Issue by joannechester** [civicrm/civicrm-user-guide#108]

**Comment by seancolsen** [comment]
We have a page on [contribution widgets](https://docs.civicrm.org/user/en/latest/contributions/widgets/) but so far all it has is a screenshot. We need some new content here explaining how contribution widgets work and why you might want to use them.

**Comment by stevekessler** [comment]
I had just looked at this recently so here is some documentation https://docs.civicrm.org/user/en/latest/contributions/widgets/  :)

**Comment by seancolsen** [comment]
**Wow** that was *fast!!!* Awesome :tada: 

Closing now because your new changes seem to address this ticket. If more work is needed we can re-open or create a new one.
