### ISSUE TITLE
Fix broken list formatting

### ISSUE THREAD

**Issue by joannechester** [civicrm/civicrm-user-guide#111]
online contributions thank and receipt tab

**Comment by seancolsen** [comment]
I'm just looking over our open issues and I wanted to offer some clarification on what I think needs to happen here...

In [this section](https://docs.civicrm.org/user/en/4.6/contributions/online-contributions/#receipt-tab) there is an unordered list displaying as a paragraph. 

**It only affects the 4.6 branch.**
