### ISSUE TITLE
Document the process for turning on advanced logging

### ISSUE THREAD

**Issue by joannechester** [civicrm/civicrm-user-guide#114]
See [this se question.](http://civicrm.stackexchange.com/questions/11556/how-to-extend-database-log-report-from-contact)

**Comment by michaelmcandrew** [comment]
Pretty sure this is not documented. This feels like an advanced system settings question to me - similar to email system settings.

**Comment by michaelmcandrew** [comment]
at least, not if the user and admin guide

**Comment by seamuslee001** [comment]
Is this covered enough here https://docs.civicrm.org/sysadmin/en/latest/setup/logging/ I have also put a PR in to add in some further information on that screen [here](https://github.com/civicrm/civicrm-sysadmin-guide/pull/77)

**Comment by seancolsen** [comment]
I'm closing this now since we have [some content about this in the Sysadmin Guide](https://docs.civicrm.org/sysadmin/en/latest/setup/logging/) as well as a [separate ticket ](https://github.com/civicrm/civicrm-sysadmin-guide/issues/79) to track further improvements to that content.
