### ISSUE TITLE
".merge_file_ZAZG0Z" and similar strings appearing in docs

### ISSUE THREAD

**Issue by twomice** [civicrm/civicrm-user-guide#126]
The page at https://docs.civicrm.org/user/en/latest/email/scheduled-reminders/ contains several blockquote elements containing only a string like ".merge_file_ZAZG0Z". Perhaps this is an artifact of some automated process?  I don't see equivalent content in the .md file (https://github.com/civicrm/civicrm-user-guide/blob/master/docs/email/scheduled-reminders.md), so creating a PR doesn't seem like it would help here.

**Comment by michaelmcandrew** [comment]
thanks, @twomice. not sure how it happened but the repo that we use to create the html from the markdown has some 'merge conflicts'. not sure how they could have arised. in tracking down the problem i deleted data that would have helped me understand how it happened. so fixed for now but might recur. Will keep an eye out and fix it properly next time.
