### ISSUE TITLE
Make "scheduled jobs" page easier for non-technical readers

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-user-guide#138]
The [scheduled jobs](https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/) section starts with reference to cron, which is a fairly technical subject. We should instead talk about the scheduled jobs UI first.

The cron references should be prefaced with "this is a job for your host or sys admin". They might want to consult the admin guide for more information.

**Comment by seancolsen** [comment]
I believe this should be addressed in #228
