### ISSUE TITLE
Vague information for Campaign Status

### ISSUE THREAD

**Issue by clnlf** [civicrm/civicrm-user-guide#143]
Offending URL: https://docs.civicrm.org/user/en/stable/campaign/set-up/
Section: Set-up > Campaign status
It says:
> Assigning a status to your campaign makes it possible to update campaign activities in the database and track how the campaign is proceeding.

What does this mean? If I knew more specifics I would put in a pull request, but unfortunately I'm not sure how 'campaign activities in the database' are affected by the campaign status

**Comment by mikaweinstein** [comment]
I poked around a little and agree that this is misleading. I don't think a campaign status has bearing on the affiliated activities in a way that's different from the campaign itself. In fact, if you search under the "Activities" tab of Advanced Search and open the campaign options, it separates out Current and Past campaigns but based on the dates listed for the campaign; it's not connected to the status at all. I think this should be changed to "Assigning a status to your campaign allows you to internally track which stage a given campaign is in." or something similar. I will make a PR with some other documentation updates later today.

**Comment by seancolsen** [comment]
Fixed with #181
