### ISSUE TITLE
Change theme to Material

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#147]
I think it would be nice to put the new Material theme in place in the User Guide? You can see it in action in the [Developer Guide](https://docs.civicrm.org/dev/en/master/). 

Is that okay with you @joannechester? I'll wait to get a go-ahead from you before making this change.

**Comment by seancolsen** [comment]
Yesterday someone wanted to edit the User Guide but got [hung up](https://chat.civicrm.org/civicrm/pl/d7bp1kxgi7nhzrwsruzxykzs3c) on the [failure](https://github.com/civicrm/civicrm-docs/issues/23) of "Edit on GitHub" to find the correct page. This minor snafu would not have happened with the Material theme. 

We've had a [lot of support](https://github.com/civicrm/civicrm-docs/issues/15) for the Material theme. Based on this support, the age of this issue, the lack of feedback here, and the difficulties that people are experiencing with readthedocs: **I will move to switch the theme to Material after 48 hours unless I hear concerns within this issue.**

**Comment by joemcl** [comment]
Not a cricket. +1 to this @seanmadsen . @joannechester this makes sense to me.
