### ISSUE TITLE
Update "Contributing to this guide"

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#166]
This page needs some updating: 
https://docs.civicrm.org/user/en/latest/the-civicrm-community/contributing-to-this-manual/

Offer a one-paragraph summary and then link to content that already exists here:
https://docs.civicrm.org/dev/en/latest/documentation/

**Comment by stevekessler** [comment]
I updated the readme.md for the user guide that is also related.

**Comment by stevekessler** [comment]
I have redone all of the documentation on documentation in this doc as well as the dev docs.  They should be much more uniform and flow together well.  

@seanmadsen that there may be a want/need in the future to combine these docs but this is a strong base for now.
