### ISSUE TITLE
CiviCRM shortcuts

### ISSUE THREAD

**Issue by AliceGa** [civicrm/civicrm-user-guide#168]
These keyboard shortcuts don't all work  https://docs.civicrm.org/user/en/4.6/the-user-interface/keyboard-shortcuts/

**Comment by seancolsen** [comment]
@AliceGa thanks for reporting this!

I just had some conversation with Coleman on Mattermost [here](https://chat.civicrm.org/civicrm/pl/6yee9p6z4385zxz5qkz18pwppw) and it sounds like this feature has been broken for several years. Thus, I think the best way to proceed is to accept that the feature does not work and remove the documentation about it. I will remove this page from the User Guide and also submit a Jira ticket to remove the help tip in the UI which advertises (some of) these shortcuts as features.

**Comment by seancolsen** [comment]
Created [CRM-20470](https://issues.civicrm.org/jira/browse/CRM-20470) to track necessary changes to CiviCRM core (removing the help icon from the UI).

**Comment by seancolsen** [comment]
Fixed in both `master` and `4.6`
