### ISSUE TITLE
Add some best practices for CiviMail templates

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#184]
We can probably take stuff from here: http://forum.civicrm.org/index.php/topic,32465.0/topicseen.html

This ticket was migrated from https://issues.civicrm.org/jira/browse/CRM-14608

**Comment by lcdservices** [comment]
I'll take a shot at drafting this.

**Comment by lcdservices** [comment]
for review: https://github.com/civicrm/civicrm-user-guide/pull/303

**Comment by seancolsen** [comment]
Resolved in #303
