### ISSUE TITLE
Fix broken images with spaces in filenames

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-user-guide#191]
May tie in well to #187.

Noticed that on https://docs.civicrm.org/user/en/4.7/advanced-configuration/email-system-configuration/#configuring-outbound-email-service there's a missing image.

![image](https://cloud.githubusercontent.com/assets/105608/26428256/cb62006e-4134-11e7-89eb-1ab505daa8d5.png)

Seems to be resolved by getting rid of the spaces in the filenames, so here's a list of other images with spaces we might need to clean up.

    img/4.5 Add Relationship.png
    img/4.5 Menubar.png
    img/AB Testing Compose Screen1.png
    img/AB Testing Metrics.png
    img/AB Testing Results Page_1.png
    img/AB Testing Targeting.png
    img/AB Testing by Subject1.png
    img/AB Testing by email1.png
    img/AB Testing.png
    img/Batch Update Contribution Via Profile.png
    img/CiviCRM 4.5 CiviCase Activities.png
    img/CiviCRM 4.5 CiviCase Standard Timeline.png
    img/CiviReport_required fields.PNG
    img/Contact Dashboard.png
    img/Contact Search.png
    img/Contribution Summary report grouping view.PNG
    img/Contribution Summary report grouping.PNG
    img/Custom Field Set.png
    img/Editing Contacts.png
    img/Event Badges UIv2.png
    img/Event Badges UIv2.png.1
    img/Event Price set v3.PNG
    img/From email.PNG
    img/GOTV tracking.jpg
    img/Groups&tags_actions Update.png
    img/Groups&tags_edit Smart Group criteria.png
    img/Import Options.png
    img/Mailing Basic Search.png
    img/Membership Pricesets non-member field_1.PNG
    img/Membership priceset final.PNG
    img/New Contribution by Contact.png
    img/New Data Entry.png
    img/PCP owner notificationV2.PNG
    img/Pledge including editing.PNG
    img/Pledge payments batch entry cropped.PNG
    img/Print contribution receipt options.PNG
    img/QA Audit Screen.PNG
    img/Repeated Event.png
    img/Repeating Events.png
    img/Repeting Event Page.png
    img/SMS types.PNG
    img/Screen Shot 2015-04-25 at 3.06.40 PM.png
    img/Screen Shot 2015-04-29 at 3.54.21 PM.png
    img/Screen shot 2011-08-27 at 16.28.28.png
    img/Search Action.PNG
    img/Search Builder.png
    img/Search Setting.png
    img/Simple housing case.PNG
    img/Tag Set - Create.png
    img/Tag Set - Creating tags on the fly.png
    img/Thank-you letters as table template.PNG
    img/Thank-you letters as table_1.PNG
    img/Thank-you letters as with smarty enabled_2.PNG
    img/Title settings 1 .jpg
    img/Viewing Contacts.png
    img/activity cf.png
    img/activity report 1.jpg
    img/activity report 2.jpg
    img/advanced search schedule mass mailing.png
    img/advanced search.PNG
    img/civiengage custom data sets small.jpg
    img/civimail_Insert image 6.jpg
    img/civimail_file directory 3.jpg
    img/civimail_window to browse server 2.jpg
    img/contact Screen -inline edit.png
    img/contact report listing.PNG
    img/contribution amounts.jpg
    img/create custom data sets.jpg
    img/create walklist survey p2.jpg
    img/create walklist survey.jpg
    img/custom data for walklists.jpg
    img/custom profile for walklist.jpg
    img/dedupe config _1.png
    img/email-dedupe config _1.png
    img/engagement index.jpg
    img/event location with warning.PNG
    img/gift membership.PNG
    img/joomla permissions_1.PNG
    img/membership contribution report.PNG
    img/membership detail from summary report.PNG
    img/membership detail report sorting criteria.PNG
    img/membership detail report sorting view.PNG
    img/membership detail report.PNG
    img/membership everyday for limited inherited.png
    img/membership everyday for limited inheritedp2.png
    img/membership lapsed report.PNG
    img/membership page receipt 1.jpg
    img/membership page receipt 2.jpg
    img/membership report list_1.PNG
    img/membership signup 1.jpg
    img/membership summary report.PNG
    img/memberships add membership new contact.JPG
    img/memberships add membership via menu.JPG
    img/memberships create new membership report_1.JPG
    img/memberships export memberships screen.JPG
    img/memberships find memberships.JPG
    img/memberships select fields to export.JPG
    img/new pledge batch_1.PNG
    img/phonebank record responses.jpg
    img/pledge batch edit.PNG
    img/pledge table.png
    img/record survey responses.jpg
    img/scheduled_reminders_other three.PNG
    img/survey report columns.PNG
    img/survey report cover.jpg
    img/survey report detail.jpg
    img/survey report p2.jpg
    img/survey set filters.jpg
    img/tell a friend.jpg
    img/walklist cover sheet.jpg
    img/walklist p2.jpg
    img/z-Sprint14 multi record old style table.png
    img/z-Sprint2014 copy multli record.png
    img/z-sprint14-membership status.png
    img/z-sprint154 - new_membership_type.png
    img/z-sprint15ipartial-payment view.png
    img/z_sprint14_Deleting memberships.png
    img/z_sprint14_Joomla!_Menu Item Type.png
    img/z_sprint14_display Results as_1.png
    img/z_sprint14_shortcode insert.png

**Comment by joannechester** [comment]
Having spaces within an image name does not cause a broken link.  I agree we we would be better of without them, but don't see this a a high priority.

**Comment by xurizaemon** [comment]
For me, removing the space did resolve the issue, so I reported it & included screenshot.

I could possibly have better phrased it: "Spaces within resource filenames may require special handling on the part of content authors, and omitting this may result in broken images."

Either way, agree it's not high priority, but it might also improve things for users (to not see missing images) and authors (to not require special treatment of filenames).

**Comment by AnneDru** [comment]
Hi - again this seems like I might be able to help with this one, but would need a hand to get started.
