### ISSUE TITLE
Infinite redircts for https://docs.civicrm.org/sysadmin/en/latest/config/message-templates

### ISSUE THREAD

**Issue by tschuettler** [civicrm/civicrm-user-guide#231]
Redirecting http://wiki.civicrm.org/confluence/display/CRMDOC/Smarty+in+mail+templates to https://docs.civicrm.org/sysadmin/en/latest/config/message-templates results in infinte redirects. 

Looks like it should resolve to https://docs.civicrm.org/sysadmin/en/latest/setup/message-templates/. 

Not to sure if this is the right place to report the issue.

**Comment by seancolsen** [comment]
Thanks for reporting! Yep, this is the right place. I'll look into this

**Comment by seancolsen** [comment]
Fixed with a combination of: 

* https://lab.civicrm.org/documentation/docs-publisher/merge_requests/83
* https://github.com/civicrm/civicrm-sysadmin-guide/commit/4c5fc2f90c51ed4b9a7df2bc590e886c70eee565
