### ISSUE TITLE
Document financial permissions

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/civicrm-user-guide#241]
See here: https://github.com/civicrm/civicrm-core/pull/7818
Note a blog post exists here: https://civicrm.org/blog/joe-murray/hiding-sensitive-contributions-from-some-staff

I could see refactoring the "permissions and ACLs" into its own chapter to accommodate this, but it's definitely not necessary.

**Comment by seancolsen** [comment]
I'm closing this ticket now because this doc has been added in #253, and I opened another ticket #256 to make it a bit more discoverable. @MegaphoneJon feel free to re-open if these changes don't address you original intent here.
