### ISSUE TITLE
Document "is public" setting for custom field groups

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#255]
The new setting for making custom field sets public/private got committed to core without any documentation. 

![mockup](https://user-images.githubusercontent.com/42411/36987279-f763aae0-2069-11e8-99c8-b3dd9953a895.png)

This page in the User Guide needs to be updated. 

https://docs.civicrm.org/user/en/latest/organising-your-data/creating-custom-fields/#custom-field-sets

How exactly does CiviCRM change its behavior based on this setting? 

As far as I can tell, this setting has only two effects:
* Custom fields attached directly to *events* are hidden from the event info page if they are part of a private custom field set
    * from https://github.com/civicrm/civicrm-core/pull/10028
* Custom fields attached to some other entities (e.g. participation, contribution, etc... *not sure of comprehensive list*) are displayed in the registration email sent to participants, but only when this email comes from a back-office registration. These fields will be hidden if they're part of a private set.
    * from https://github.com/civicrm/civicrm-core/pull/10661

**Comment by seancolsen** [comment]
See also: ticket to track changes to Core in order to add help text to the UI https://lab.civicrm.org/dev/core/issues/6

**Comment by dvhirst** [comment]
2018 03 23; 17:50 US/PDT - I'm on this one.  At the stage of reviewing existing material.  It looks like an image needs to be replaced, and some additional words created.  I'll update this comment when I'm further along. 

2018 03 24; 22:50 US/PDT - not much progress, further analysis of impact is needed, I'll work on it over the next couple of days.

**Comment by mattwire** [comment]
@monishdeb @jitendrapurohit Can either of you comment on this as it's not clear what the new option does and looks like you were involved in the PR that added it?

**Comment by jitendrapurohit** [comment]
Hi @seanmadsen @mattwire Thanks for the ping. This setting is only applicable to event custom sets, i.e -

- Non-public sets are not shown on the Event Info page.
- It will not be included in the event receipt template sent to the participant after registration.

I've raised a PR for the doc at https://github.com/civicrm/civicrm-user-guide/pull/338

**Comment by seamuslee001** [comment]
This was addressed in #351 and also added via https://github.com/civicrm/civicrm-core/pull/13060 closing
