### ISSUE TITLE
Crossreference financial type permissions from financial type section

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-user-guide#256]
As a follow up to #253 we should add a note in this section...

https://docs.civicrm.org/user/en/latest/contributions/key-concepts-and-configurations/#financial-types

which points readers to this section:

https://docs.civicrm.org/user/en/latest/initial-set-up/permissions-and-access-control/#financial-type-permissions

**Comment by abihazakariya** [comment]
I'll work on this.

**Comment by seancolsen** [comment]
Fixed with https://github.com/civicrm/civicrm-user-guide/pull/274 and https://github.com/civicrm/civicrm-user-guide/pull/276
