### ISSUE TITLE
Fix a handful of broken references

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-user-guide#261]
Following on from civicrm/civicrm-dev-docs#498

**Comment by joannechester** [comment]
No  About half our image titles include uppercase letters.  For example, I can see an image  showing the "New tag set" form at https://docs.civicrm.org/user/en/latest/organising-your-data/groups-and-tags/#tag-sets .  That image is calledTag Set - Create.png  so it has uppercase ( and spaces)

**Comment by xurizaemon** [comment]
WEIRD. Thanks for checking Joanne. So - for 623eaad, do you see [this image](https://github.com/civicrm/civicrm-user-guide/blob/master/docs/img/Wordpress-Shortcodes-small.png) in [this page](https://docs.civicrm.org/user/en/latest/membership/online-membership-sign-up/)? I don't, and I did not see it locally until I made that change, upon which it appeared.

The image should appear below the phrase "any page or post".

**Comment by joannechester** [comment]
No, and I can't work out why.

**Comment by seancolsen** [comment]
The image was not loading because the markdown had `WordPress` and the filename had `Wordpress`. No cause for alarm. Chris' changes in #262 fixed it.
