### ISSUE TITLE
Remove permissions for anonymous users section

### ISSUE THREAD

**Issue by wmortada** [civicrm/civicrm-user-guide#270]
The [Permissions for anonymous users](https://docs.civicrm.org/user/en/latest/initial-set-up/installation-and-basic-set-up/#permissions-for-anonymous-users) section under [Installation and basic set up](https://docs.civicrm.org/user/en/latest/initial-set-up/installation-and-basic-set-up/) doesn't make much sense.  I'm not sure if it's needed as it is covered under [Permissions and access control](https://docs.civicrm.org/user/en/latest/initial-set-up/permissions-and-access-control/#anonymous-and-authenticated-roles).

**Comment by seancolsen** [comment]
I agree that we should remove that section.

**Comment by wmortada** [comment]
Thanks @seanmadsen
