### ISSUE TITLE
Clarify permissions for 'profile listings and forms'

### ISSUE THREAD

**Issue by wmortada** [civicrm/civicrm-user-guide#355]
I found the section on '[Using the "Profile listings and forms" permission](https://docs.civicrm.org/user/en/latest/initial-set-up/permissions-and-access-control/#using-the-profile-listings-and-forms-permission)' a bit unclear.  I think it could be made clearer.

I have spent some time trying to understand exactly what the 'profile listing and forms' permission does.  I believe that it is basically just a shortcut for applying all four separate permissions relating to profiles:

- profile create
- profile view
- profile edit
- profile listings

Could someone please confirm if this is true?  If so, I would suggest that we make this explicit in the documentation.  If not, I think we need to explain what this permission is more clearly.

**Comment by homotechsual** [comment]
Yes, you're correct that the permission is a shortcut for the 4 permissions listed.

See https://github.com/civicrm/civicrm-core/blob/08cf6bdfcfcbfa51ff972dc214f3aa82c606efc7/CRM/Core/Permission.php from line 317

**Comment by homotechsual** [comment]
This has been updated in the docs repo (see: https://github.com/civicrm/civicrm-user-guide/blob/master/docs/initial-set-up/permissions-and-access-control.md) but is stalled pending resolution of https://lab.civicrm.org/infrastructure/ops/issues/844

**Comment by wmortada** [comment]
Many thanks for the confirmation and for making the change to the documentation.

**Comment by wmortada** [comment]
I think the documentation is much clearer than I remember it from two years ago, but I think it would be better if it was completely explicit on this point. Should we add a line that says something along the lines of:

`profile_listing_and_forms` = `profile_view` + `profile_create` + `profile_edit` + `profile_listing`

?

**Comment by homotechsual** [comment]
That sounds good to me!

**Comment by homotechsual** [comment]
Linked a PR.

**Comment by wmortada** [comment]
Thanks @MikeyMJCO
