### ISSUE TITLE
Documentation for Group ID is not (any longer?) accurate

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-user-guide#380]
At https://docs.civicrm.org/user/en/latest/organising-your-data/groups-and-tags/#group-ids

>  For example, the group ID can be used to define a URL for group sign-ups. You can find a group's ID by checking the ID column in the tabled list of groups at Navigation Menu > Contacts > Manage Groups.

But

![Screenshot from 2019-04-15 22-26-42](https://user-images.githubusercontent.com/105608/56125699-9daff680-5fcd-11e9-8687-813173890649.png)

So I think that sentence needs a re-word, unless something's funny about dmaster?

**Comment by xurizaemon** [comment]
Looks like this was changed in CRM-15107 / civicrm/civicrm-core@7f4b344c

**Comment by homotechsual** [comment]
Fixed 6932330
