### ISSUE TITLE
Update ref to 'transgender' per https://lab.civicrm.org/dev/core/issues/993#note_18259

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-user-guide#388]

**Comment by homotechsual** [comment]
A search of the docs leads me to conclude that there aren't any mentions of transgender and a scan of the images on pages mentioning gender don't reveal any which show outdated options.

**Comment by eileenmcnaughton** [comment]
Hmm he said "Indeed, I apologize. It wasn't on a latest version of CiviCRM. I was mistaken because I saw this option described on the french version of the user manual.
"

I wonder if the French version has it or he was just looking at an old version

**Comment by homotechsual** [comment]
Didn't check the french version! Will need to ask a french speaker/reader to check on that one. Will ping the french channel/repo with an issue.

**Comment by oTelle** [comment]
Just checked the french version: there aren't any mention of transgender anymore. The french manual has some English parts not yet translated, and it was in it. I think I removed the term (in an example) when I translated the page 'Contacts' into French.

**Comment by homotechsual** [comment]
Thanks @oTelle :-)

Closing this issue.
