### ISSUE TITLE
Document "smart group cache timeout" setting.

### ISSUE THREAD

**Issue by homotechsual** [civicrm/civicrm-user-guide#399]
From #397 

> Thanks @eileenmcnaughton. Very useful.
> 
> As @michaelmcandrew asks here https://civicrm.stackexchange.com/q/31303/104 maybe it would be missing to document Administer > Customize Data and Screens > Search Preferences 'Smart group cache timeout' setting. I personally continue without being completely clear what is its purpose.

**Comment by eileenmcnaughton** [comment]
Basically when you go to access a group it goes

1) does a cache for the group exist?
2) yes - is it expired?
3) yes - empty it 
4) refill it and set the timeout to now + the Smart group cache timeout

If the smart group cache time out is 0 the cache will not be filled & will be recalculated every time. Depending on the site  this can be faster or slower than using a cache
- was thi

**Comment by homotechsual** [comment]
This is currently covered here:

https://docs.civicrm.org/user/en/latest/organising-your-data/smart-groups/#smart-group-caching

I'll raise a PR to clarify how the caching works in this section and perhaps to link to this page from the jobs page.

**Comment by homotechsual** [comment]
Documented in referenced PR.
