### ISSUE TITLE
Screenshot  for event location  page needs updating

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-user-guide#425]
Per  this PR https://github.com/civicrm/civicrm-core/pull/16230 there is  a new check box that needs to be added  to the PR

**Comment by homotechsual** [comment]
This is resolved but should have been done as a PR rather than a direct commit - so that we could merge it when the checkbox actually shows up in the UI.

**Comment by seamuslee001** [comment]
@MikeyMJCO just noting it is a PR here https://github.com/civicrm/civicrm-user-guide/pull/426 that is saying i made a commit onto my fork not into the core repo

**Comment by homotechsual** [comment]
My bad Seamus!
